#include "web_ui.h"

const char *web_ui_index_html(void) {
    return
        "<!doctype html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "  <meta charset=\"utf-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        "  <title>Katana Foot</title>\n"
        "  <style>\n"
        "    :root{color-scheme:dark;--bg:#111417;--panel:#1b2127;--line:#2d3945;--accent:#2fb7ff;--fx:#ff8a29;--solo:#ff4d4d;--muted:#8ba0b3;--text:#f3f7fb;--ok:#45d483;--warn:#ffd166}\n"
        "    *{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#243140 0,#111417 48%);color:var(--text);font:16px/1.45 ui-sans-serif,system-ui,sans-serif}\n"
        "    main{max-width:920px;margin:0 auto;padding:24px 16px 40px}h1,h2{margin:0 0 8px}h1{font-size:1.7rem}h2{font-size:1.1rem}p{margin:0;color:var(--muted)}\n"
        "    .section{margin-top:22px}.status,.grid,.utility,.mapping-grid{display:grid;gap:12px}.status{grid-template-columns:repeat(4,minmax(0,1fr));margin-top:18px}.grid{grid-template-columns:repeat(2,minmax(0,1fr));margin-top:18px}.utility{grid-template-columns:repeat(3,minmax(0,1fr));margin-top:18px}.mapping-grid{grid-template-columns:repeat(2,minmax(0,1fr));margin-top:14px}\n"
        "    .card,.switch,form{background:rgba(27,33,39,.86);border:1px solid var(--line);border-radius:18px;backdrop-filter:blur(14px)}.card,form{padding:14px}.metric{font-size:.8rem;color:var(--muted);text-transform:uppercase;letter-spacing:.08em}.value{margin-top:6px;font-size:1rem;font-weight:700}\n"
        "    .switch{padding:18px;min-height:96px;display:flex;flex-direction:column;justify-content:space-between}.switch strong{font-size:1.1rem}\n"
        "    button{border:0;border-radius:16px;background:#25303a;color:var(--text);padding:14px 12px;font:inherit;font-weight:700;cursor:pointer}button.active{background:var(--accent);color:#061018}button.fx.active{background:var(--fx);color:#1a0d00}button.solo.active{background:var(--solo);color:#fff}button.secondary{background:#182028;border:1px solid var(--line)}button.warn{background:#3a2f12;color:#ffe6a7}button:disabled{opacity:.45;cursor:not-allowed}\n"
        "    label{display:grid;gap:6px;font-size:.92rem;color:var(--muted)}input,select{width:100%;padding:12px 14px;border-radius:12px;border:1px solid var(--line);background:#10161c;color:var(--text)}\n"
        "    .row{display:flex;gap:10px;flex-wrap:wrap}.hint{font-size:.86rem;color:var(--muted)}.pill{display:inline-flex;align-items:center;gap:8px;padding:8px 10px;border-radius:999px;background:#151c22;border:1px solid var(--line);font-size:.88rem;color:var(--muted)}.pill strong{color:var(--text)}\n"
        "    .ok{color:var(--ok)}.warn-text{color:var(--warn)}\n"
        "    @media (max-width:760px){.status{grid-template-columns:repeat(2,minmax(0,1fr))}.utility,.mapping-grid{grid-template-columns:1fr}}@media (max-width:560px){.status,.grid{grid-template-columns:1fr}}\n"
        "  </style>\n"
        "</head>\n"
        "<body>\n"
        "  <main>\n"
        "    <h1>Katana Foot</h1>\n"
        "    <p>Gen 3 BLE-MIDI footswitch with configurable PC/CC mapping.</p>\n"
        "\n"
        "    <section class=\"status section\">\n"
        "      <div class=\"card\"><div class=\"metric\">Mode</div><div class=\"value\" id=\"modeValue\">preset</div></div>\n"
        "      <div class=\"card\"><div class=\"metric\">BLE / WiFi</div><div class=\"value\" id=\"linkValue\">connecting</div></div>\n"
        "      <div class=\"card\"><div class=\"metric\">Preset</div><div class=\"value\" id=\"presetValue\">A1</div></div>\n"
        "      <div class=\"card\"><div class=\"metric\">Confidence</div><div class=\"value\" id=\"confidenceValue\">none</div></div>\n"
        "    </section>\n"
        "\n"
        "    <section class=\"section\">\n"
        "      <div class=\"row\">\n"
        "        <span class=\"pill\"><strong>MIDI</strong> <span id=\"midiConfiguredBadge\">not calibrated</span></span>\n"
        "        <span class=\"pill\"><strong>SOLO</strong> <span id=\"soloConfiguredBadge\">not configured</span></span>\n"
        "        <span class=\"pill\"><strong>Offset</strong> <span id=\"offsetBadge\">unknown</span></span>\n"
        "      </div>\n"
        "    </section>\n"
        "\n"
        "    <section class=\"grid section\" id=\"footswitchGrid\"></section>\n"
        "\n"
        "    <section class=\"utility section\">\n"
        "      <button id=\"soloButton\" class=\"solo\" type=\"button\">Solo</button>\n"
        "      <button id=\"modeButton\" type=\"button\">Toggle Mode</button>\n"
        "      <button id=\"reverbButton\" class=\"fx\" type=\"button\">Reverb</button>\n"
        "      <button id=\"reconnectButton\" class=\"secondary\" type=\"button\">Reconnect BLE</button>\n"
        "      <button id=\"resyncButton\" class=\"secondary\" type=\"button\">Resync</button>\n"
        "      <button id=\"wifiResetButton\" class=\"warn\" type=\"button\">Reset WiFi</button>\n"
        "    </section>\n"
        "\n"
        "    <section class=\"section\">\n"
        "      <form id=\"midiConfigForm\">\n"
        "        <h2>Gen 3 MIDI Setup</h2>\n"
        "        <p>Use BTS-visible numbering here. Offset calibration decides whether visible PC 1 is sent on the wire as 0 or 1.</p>\n"
        "        <div class=\"mapping-grid\">\n"
        "          <label>PC Panel<input id=\"pcPanel\" type=\"number\" min=\"0\" max=\"127\"></label>\n"
        "          <label>PC Offset<select id=\"pcOffsetMode\"><option value=\"unknown\">Unknown</option><option value=\"subtract-one\">BTS 1 => wire 0</option><option value=\"direct\">BTS 1 => wire 1</option></select></label>\n"
        "          <label>PC A1<input id=\"pcA1\" type=\"number\" min=\"0\" max=\"127\"></label>\n"
        "          <label>PC A2<input id=\"pcA2\" type=\"number\" min=\"0\" max=\"127\"></label>\n"
        "          <label>PC B1<input id=\"pcB1\" type=\"number\" min=\"0\" max=\"127\"></label>\n"
        "          <label>PC B2<input id=\"pcB2\" type=\"number\" min=\"0\" max=\"127\"></label>\n"
        "          <label>CC Booster<input id=\"ccBooster\" type=\"number\" min=\"0\" max=\"127\"></label>\n"
        "          <label>CC Mod<input id=\"ccMod\" type=\"number\" min=\"0\" max=\"127\"></label>\n"
        "          <label>CC FX<input id=\"ccFx\" type=\"number\" min=\"0\" max=\"127\"></label>\n"
        "          <label>CC Delay<input id=\"ccDelay\" type=\"number\" min=\"0\" max=\"127\"></label>\n"
        "          <label>CC Reverb<input id=\"ccReverb\" type=\"number\" min=\"0\" max=\"127\"></label>\n"
        "          <label>CC Send/Return<input id=\"ccSendReturn\" type=\"number\" min=\"0\" max=\"127\"></label>\n"
        "          <label>SOLO configured<select id=\"soloConfigured\"><option value=\"false\">No</option><option value=\"true\">Yes</option></select></label>\n"
        "          <label>CC Solo<input id=\"ccSolo\" type=\"number\" min=\"0\" max=\"127\"></label>\n"
        "        </div>\n"
        "        <div class=\"row\" style=\"margin-top:14px\">\n"
        "          <button type=\"submit\">Save MIDI Mapping</button>\n"
        "          <button id=\"testSubtractOne\" class=\"secondary\" type=\"button\">Test A1 as BTS-1 => wire 0</button>\n"
        "          <button id=\"testDirect\" class=\"secondary\" type=\"button\">Test A1 as BTS-1 => wire 1</button>\n"
        "        </div>\n"
        "        <div class=\"hint\" id=\"midiConfigHint\">Preset switching stays disabled until the PC offset is calibrated.</div>\n"
        "      </form>\n"
        "    </section>\n"
        "\n"
        "    <section class=\"section\">\n"
        "      <form id=\"wifiForm\">\n"
        "        <h2>WiFi Provisioning</h2>\n"
        "        <p>Shown on first boot or after WiFi reset.</p>\n"
        "        <div class=\"mapping-grid\">\n"
        "          <label>SSID<input id=\"ssid\" name=\"ssid\" autocomplete=\"username\"></label>\n"
        "          <label>Password<input id=\"password\" name=\"password\" type=\"password\" autocomplete=\"current-password\"></label>\n"
        "        </div>\n"
        "        <div class=\"row\" style=\"margin-top:14px\"><button type=\"submit\">Save WiFi</button></div>\n"
        "      </form>\n"
        "    </section>\n"
        "  </main>\n"
        "  <script>\n"
        "    const presetButtons=[['A1','preset.select','A1'],['A2','preset.select','A2'],['B1','preset.select','B1'],['B2','preset.select','B2']];\n"
        "    const effectButtons=[['Booster','effect.toggle','booster'],['Mod','effect.toggle','mod'],['FX','effect.toggle','fx'],['Delay','effect.toggle','delay']];\n"
        "    const state={footswitchMode:'preset',activePreset:'A1',soloEnabled:false,effects:{booster:false,mod:false,fx:false,delay:false,reverb:false},synced:false,wifiProvisioned:false,bleState:'disconnected',wifiState:'unprovisioned',midiConfigured:false,soloConfigured:false,pcOffsetMode:'unknown',ampStateConfidence:'none'};\n"
        "    const midiConfig={pcPanel:5,pcA1:1,pcA2:2,pcB1:6,pcB2:7,ccBooster:16,ccMod:17,ccFx:18,ccDelay:19,ccReverb:20,ccSendReturn:21,soloConfigured:false,ccSolo:0,pcOffsetMode:'unknown'};\n"
        "    const grid=document.getElementById('footswitchGrid');\n"
        "    const fields=['pcPanel','pcA1','pcA2','pcB1','pcB2','ccBooster','ccMod','ccFx','ccDelay','ccReverb','ccSendReturn','ccSolo'];\n"
        "    async function postJSON(url,body){const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!res.ok)throw new Error(await res.text());return res.headers.get('content-type')?.includes('application/json')?res.json():res.text();}\n"
        "    async function send(action,payload={}){return postJSON('/api/action',{action,...payload});}\n"
        "    function renderButtons(){grid.innerHTML='';const entries=state.footswitchMode==='preset'?presetButtons:effectButtons;entries.forEach(([label,action,value])=>{const btn=document.createElement('button');btn.type='button';btn.className='switch'+(state.footswitchMode==='effect'?' fx':'');const active=state.footswitchMode==='preset'?state.activePreset===value:state.effects[value];if(active)btn.classList.add('active');if(state.footswitchMode==='preset'&&!state.midiConfigured)btn.disabled=true;btn.innerHTML='<strong>'+label+'</strong><span>'+(state.footswitchMode==='preset'?'Program Change':'Control Change')+'</span>';btn.onclick=()=>send(action,state.footswitchMode==='preset'?{preset:value}:{effect:value}).catch(showError);grid.appendChild(btn);});const soloBtn=document.getElementById('soloButton');soloBtn.classList.toggle('active',state.soloEnabled);soloBtn.disabled=!state.soloConfigured;soloBtn.title=state.soloConfigured?'':'Configure SOLO CC first';const reverbBtn=document.getElementById('reverbButton');reverbBtn.classList.toggle('active',state.effects.reverb);}\n"
        "    function renderStatus(){document.getElementById('modeValue').textContent=state.footswitchMode;document.getElementById('linkValue').textContent=state.bleState+' / '+state.wifiState;document.getElementById('presetValue').textContent=state.activePreset;document.getElementById('confidenceValue').textContent=state.ampStateConfidence+(state.synced?'':' (local)');document.getElementById('wifiForm').style.display=state.wifiProvisioned?'none':'grid';document.getElementById('midiConfiguredBadge').textContent=state.midiConfigured?'ready':'not calibrated';document.getElementById('soloConfiguredBadge').textContent=state.soloConfigured?'configured':'not configured';document.getElementById('offsetBadge').textContent=state.pcOffsetMode;document.getElementById('midiConfigHint').innerHTML=state.midiConfigured?'<span class=\"ok\">Preset switching is enabled.</span>':'<span class=\"warn-text\">Preset switching stays disabled until the PC offset is calibrated.</span>';}\n"
        "    function renderMidiConfig(){fields.forEach((key)=>{document.getElementById(key).value=midiConfig[key];});document.getElementById('soloConfigured').value=String(midiConfig.soloConfigured);document.getElementById('pcOffsetMode').value=midiConfig.pcOffsetMode;}\n"
        "    function applyState(next){Object.assign(state,next);if(next.effects)state.effects=next.effects;renderButtons();renderStatus();}\n"
        "    function applyMidiConfig(next){Object.assign(midiConfig,next);renderMidiConfig();}\n"
        "    async function loadState(){const res=await fetch('/api/state');applyState(await res.json());}\n"
        "    async function loadMidiConfig(){const res=await fetch('/api/midi-config');applyMidiConfig(await res.json());}\n"
        "    function collectMidiConfig(){const payload={soloConfigured:document.getElementById('soloConfigured').value==='true',pcOffsetMode:document.getElementById('pcOffsetMode').value};fields.forEach((key)=>payload[key]=Number(document.getElementById(key).value));return payload;}\n"
        "    function showError(err){alert(typeof err==='string'?err:(err?.message||'Request failed'));}\n"
        "    async function runCalibration(candidate){try{await postJSON('/api/midi-calibrate',{candidate,preset:'A1'});const ok=confirm('Switched the amp to A1? Click OK to store this offset, Cancel to keep testing.');if(ok){await postJSON('/api/midi-calibrate',{candidate,preset:'A1',confirm:true});await Promise.all([loadMidiConfig(),loadState()]);}}catch(err){showError(err);}}\n"
        "    document.getElementById('soloButton').onclick=()=>send('solo.toggle').catch(showError);\n"
        "    document.getElementById('modeButton').onclick=()=>send('mode.set',{mode:state.footswitchMode==='preset'?'effect':'preset'}).catch(showError);\n"
        "    document.getElementById('reverbButton').onclick=()=>send('effect.toggle',{effect:'reverb'}).catch(showError);\n"
        "    document.getElementById('reconnectButton').onclick=()=>send('ble.reconnect').catch(showError);\n"
        "    document.getElementById('resyncButton').onclick=()=>send('resync').catch(showError);\n"
        "    document.getElementById('wifiResetButton').onclick=()=>send('wifi.reset').catch(showError);\n"
        "    document.getElementById('midiConfigForm').addEventListener('submit',async(e)=>{e.preventDefault();try{const result=await postJSON('/api/midi-config',collectMidiConfig());applyMidiConfig(result);await loadState();}catch(err){showError(err);}});\n"
        "    document.getElementById('testSubtractOne').onclick=()=>runCalibration('subtract-one');\n"
        "    document.getElementById('testDirect').onclick=()=>runCalibration('direct');\n"
        "    document.getElementById('wifiForm').addEventListener('submit',async(e)=>{e.preventDefault();try{await postJSON('/api/provision',{ssid:document.getElementById('ssid').value,password:document.getElementById('password').value});}catch(err){showError(err);}});\n"
        "    const ws=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/ws');ws.onmessage=(event)=>applyState(JSON.parse(event.data));ws.onclose=()=>setTimeout(()=>loadState().catch(()=>{}),1500);\n"
        "    Promise.all([loadState(),loadMidiConfig()]).catch(showError);\n"
        "  </script>\n"
        "</body>\n"
        "</html>\n";
}
